#spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
#spring.datasource.username=root
#spring.datasource.password=Amit@123
#
#spring.jpa.hibernate.ddl-auto=update
#server.servlet.context-path=/api/v1.0


spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
spring.datasource.username=root
spring.datasource.password=Amit@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.context-path=/api/v1.0

aws.access.key=your_access_key
aws.secret.key=your_secret_key
aws.region=ap-south-1
aws.bucket.name=your_bucket_name

jwt.secret.key=thisismysecretkeyfortheplacement

razorpay.key.id=rzp_live_SiKTQxe188AxK9
razorpay.key.secret=jf4t90WL1TckWx4mfCxtHOHr